#!/usr/bin/env python3
"""Cross-system comparisons for geometric metrics generated by md geom."""

from __future__ import annotations

import csv
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


@dataclass(frozen=True)
class GeomMetricSeries:
    system_name: str
    system_dir: Path
    metrics_file: Path
    label: str
    values: tuple[float, ...]


def find_geom_metrics_files(system_dir: Path, metrics_filename: str | None = None) -> list[Path]:
    if metrics_filename:
        candidate = system_dir / metrics_filename
        return [candidate] if candidate.is_file() else []
    return sorted(system_dir.glob("*_metrics.csv"))


def read_metric_labels(metrics_file: Path) -> list[str]:
    with metrics_file.open(newline="", encoding="utf-8") as fh:
        reader = csv.reader(fh)
        try:
            headers = next(reader)
        except StopIteration:
            return []
    return [header for header in headers if header not in {"frame", "time_ps"}]


def read_metric_values(metrics_file: Path, label: str) -> list[float]:
    values: list[float] = []
    with metrics_file.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        if not reader.fieldnames or label not in reader.fieldnames:
            return []
        for row in reader:
            text = (row.get(label) or "").strip()
            if not text:
                continue
            try:
                value = float(text)
            except ValueError:
                continue
            if not math.isnan(value):
                values.append(value)
    return values


def discover_geom_analysis_dirs(base_dir: Path, metrics_filename: str | None = None) -> list[Path]:
    dirs = []
    for entry in sorted(base_dir.iterdir()):
        if not entry.is_dir():
            continue
        if find_geom_metrics_files(entry, metrics_filename):
            dirs.append(entry)
    return dirs


def collect_metric_label_map(system_dirs: Sequence[Path], metrics_filename: str | None = None) -> dict[str, list[Path]]:
    label_to_dirs: dict[str, list[Path]] = {}
    for system_dir in system_dirs:
        labels = set()
        for metrics_file in find_geom_metrics_files(system_dir, metrics_filename):
            labels.update(read_metric_labels(metrics_file))
        for label in labels:
            label_to_dirs.setdefault(label, []).append(system_dir)
    return label_to_dirs


def collect_geom_metric_series(
    system_dirs: Sequence[Path],
    label: str,
    metrics_filename: str | None = None,
) -> tuple[list[GeomMetricSeries], list[tuple[Path, str]]]:
    series = []
    missing = []
    for system_dir in system_dirs:
        found: GeomMetricSeries | None = None
        for metrics_file in find_geom_metrics_files(system_dir, metrics_filename):
            values = read_metric_values(metrics_file, label)
            if values:
                found = GeomMetricSeries(
                    system_name=system_dir.name,
                    system_dir=system_dir,
                    metrics_file=metrics_file,
                    label=label,
                    values=tuple(values),
                )
                break
        if found is None:
            missing.append((system_dir, label))
        else:
            series.append(found)
    return series, missing


def parse_bins_spec(text: str | int) -> str | int:
    if isinstance(text, int):
        if text < 1:
            raise ValueError("La cantidad de bins debe ser >= 1.")
        return text
    token = str(text).strip().lower()
    if token.isdigit():
        value = int(token)
        if value < 1:
            raise ValueError("La cantidad de bins debe ser >= 1.")
        return value
    if token in {"fd", "auto", "sturges", "sqrt", "rice", "doane", "scott"}:
        return token
    raise ValueError("Bins invalido. Usar un entero o fd, auto, sturges, sqrt, rice, doane, scott.")


def central_range(values_by_system: Iterable[Sequence[float]], percentile: float = 100.0) -> tuple[float, float] | None:
    values = [value for values in values_by_system for value in values if not math.isnan(value)]
    if not values:
        return None
    if percentile >= 100.0:
        xmin = min(values)
        xmax = max(values)
    else:
        try:
            import numpy as np
        except ImportError:
            xmin = min(values)
            xmax = max(values)
        else:
            tail = 0.5 * (100.0 - percentile)
            xmin, xmax = [float(v) for v in np.percentile(values, [tail, 100.0 - tail])]
    if xmin == xmax:
        pad = max(abs(xmin) * 0.05, 1e-3)
        return xmin - pad, xmax + pad
    pad = 0.05 * (xmax - xmin)
    return xmin - pad, xmax + pad


def write_geom_compare_values(output_dir: Path, label: str, series: Sequence[GeomMetricSeries]) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"geom_compare_{safe_token(label)}_values.csv"
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["system", "metric", "value"])
        for item in series:
            for value in item.values:
                writer.writerow([item.system_name, label, f"{value:.9f}"])
    return out_path


def write_geom_compare_summary(output_dir: Path, label: str, series: Sequence[GeomMetricSeries]) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"geom_compare_{safe_token(label)}_summary.csv"
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["system", "metric", "n", "min", "max", "mean", "std", "metrics_file"])
        for item in series:
            values = list(item.values)
            mean = sum(values) / len(values)
            var = sum((value - mean) ** 2 for value in values) / len(values)
            writer.writerow(
                [
                    item.system_name,
                    label,
                    len(values),
                    f"{min(values):.9f}",
                    f"{max(values):.9f}",
                    f"{mean:.9f}",
                    f"{math.sqrt(var):.9f}",
                    str(item.metrics_file),
                ]
            )
    return out_path


def make_geom_overlay_histogram(
    series: Sequence[GeomMetricSeries],
    label: str,
    output_path: Path,
    bins_spec: str | int = "fd",
    percentile: float = 100.0,
    show_kde: bool = True,
    kde_smooth: float = 2.5,
    kde_prominence: float = 0.08,
    modes_path: Path | None = None,
    annotate: bool = True,
) -> Path:
    if not series:
        raise ValueError("No hay datos para graficar.")

    try:
        mpl_config = Path(".matplotlib-cache").resolve()
        mpl_config.mkdir(exist_ok=True)
        os.environ.setdefault("MPLCONFIGDIR", str(mpl_config))
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError as exc:
        raise RuntimeError("No se pudo importar matplotlib/numpy para graficar.") from exc

    plot_range = central_range((item.values for item in series), percentile=percentile)
    pooled = np.array([value for item in series for value in item.values], dtype=float)
    if plot_range is not None:
        pooled = pooled[(pooled >= plot_range[0]) & (pooled <= plot_range[1])]
    if pooled.size == 0:
        raise ValueError("No quedaron datos dentro del rango de ploteo.")

    if isinstance(bins_spec, int):
        edges = np.linspace(plot_range[0], plot_range[1], bins_spec + 1) if plot_range else bins_spec
    else:
        edges = np.histogram_bin_edges(pooled, bins=bins_spec, range=plot_range)

    fig, ax = plt.subplots(figsize=(9, 6), constrained_layout=True)
    cmap = plt.get_cmap("tab10")
    modes_rows = []
    for idx, item in enumerate(series):
        values = np.array(item.values, dtype=float)
        if plot_range is not None:
            values = values[(values >= plot_range[0]) & (values <= plot_range[1])]
        if values.size == 0:
            continue
        color = cmap(idx % 10)
        ax.hist(
            values,
            bins=edges,
            density=True,
            alpha=0.32,
            color=color,
            edgecolor=color,
            linewidth=0.7,
            label=f"{item.system_name} (n={values.size})" if annotate else None,
        )
        if show_kde and values.size > 1 and len(set(float(v) for v in values)) > 1:
            try:
                from scipy.stats import gaussian_kde
            except ImportError:
                pass
            else:
                xmin, xmax = plot_range if plot_range is not None else (float(values.min()), float(values.max()))
                xs = np.linspace(xmin, xmax, 250)
                kde = gaussian_kde(values, bw_method=scaled_scott_bandwidth(kde_smooth))
                dens = kde(xs)
                ax.plot(xs, dens, color=color, linewidth=1.8)
                modes_rows.extend(find_relevant_kde_modes(item.system_name, xs, dens, kde_prominence))

    if plot_range is not None:
        ax.set_xlim(plot_range)
    if annotate:
        ax.set_xlabel(label)
        ax.set_ylabel("density")
        ax.set_title(f"Comparacion global: {label}")
        ax.grid(True, alpha=0.25)
    else:
        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.set_title("")
        ax.tick_params(labelbottom=False, labelleft=False)
    if annotate:
        ax.legend(fontsize=8)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300)
    plt.close(fig)
    if modes_path is not None and show_kde:
        write_kde_modes(modes_path, label, modes_rows)
    return output_path


def scaled_scott_bandwidth(scale_factor: float):
    if scale_factor <= 0.0:
        raise ValueError("El suavizado KDE debe ser > 0.")

    def bandwidth(kde):
        return kde.scotts_factor() * scale_factor

    return bandwidth


def find_relevant_kde_modes(system_name: str, xs, dens, prominence_fraction: float) -> list[tuple[str, float, float, float]]:
    if prominence_fraction < 0.0:
        raise ValueError("La prominencia KDE debe ser >= 0.")
    if len(xs) == 0 or len(dens) == 0:
        return []
    try:
        from scipy.signal import find_peaks
    except ImportError:
        peak_index = int(dens.argmax())
        return [(system_name, float(xs[peak_index]), float(dens[peak_index]), 1.0)]

    max_density = float(dens.max())
    if max_density <= 0.0:
        return []
    peaks, props = find_peaks(dens, prominence=prominence_fraction * max_density)
    if len(peaks) == 0:
        peak_index = int(dens.argmax())
        return [(system_name, float(xs[peak_index]), float(dens[peak_index]), 1.0)]

    prominences = props.get("prominences", [])
    modes = []
    for peak_index, prominence in zip(peaks, prominences):
        modes.append(
            (
                system_name,
                float(xs[peak_index]),
                float(dens[peak_index]),
                float(prominence) / max_density,
            )
        )
    return sorted(modes, key=lambda row: row[2], reverse=True)


def write_kde_modes(modes_path: Path, label: str, modes_rows: Sequence[tuple[str, float, float, float]]) -> Path:
    modes_path.parent.mkdir(parents=True, exist_ok=True)
    with modes_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["system", "metric", "mode_value", "density", "relative_prominence"])
        for system_name, mode_value, density, relative_prominence in modes_rows:
            writer.writerow(
                [
                    system_name,
                    label,
                    f"{mode_value:.9f}",
                    f"{density:.9f}",
                    f"{relative_prominence:.6f}",
                ]
            )
    return modes_path


def safe_token(text: str) -> str:
    token = "".join(ch if ch.isalnum() or ch in {"-", "_"} else "_" for ch in text.strip())
    return token or "metric"
